<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>健康助手</RootNamespace>
    <AssemblyName>健康助手</AssemblyName>
    <ApplicationIcon>Resources\app.ico</ApplicationIcon>
    <SatelliteResourceLanguages>zh-Hans</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Fonts\FusionPixel12.ttf" />
    <None Include="Fonts\OFL.txt" />
  </ItemGroup>

</Project>
